### ISSUE TITLE
Can I use this to change the icon color of a group in glance card?

### ISSUE THREAD

**Issue by rdehuyss** [thomasloven/lovelace-card-modder#12]
Hi Thomas,

I would love to change the color of some group icons depending on the state of the group (on or off) in a glance card.

Can I use this custom card for that? I don't see however which css rule I would need to change though.

Thx,
R

**Comment by thomasloven** [comment]
The css variable you want is the one in the very first example in the readme.

You'd need some way to translate the state to a color, though. E.g. a template sensor.
