### ISSUE TITLE
Card-modder with markdown

### ISSUE THREAD

**Issue by thib5** [thomasloven/lovelace-card-modder#15]
Hi, I'm trying to applied card-modder to a Markdown card

    - type: markdown
      content: >
       [Appartement](http://192.168.0.85:8765)

            style:
              border-radius: 5px
              border: 'solid 1px rgba(255,255,255,1)'
              box-shadow: '3px 3px rgba(0,0,0,0.4)'

how can I do that ?

**Comment by thomasloven** [comment]
By correcting your indentation. Look at the samples.
