### ISSUE TITLE
Styling per CSS selectors

### ISSUE THREAD

**Issue by yosilevy** [thomasloven/lovelace-card-modder#19]
Sometimes styles need to be applied only to certain elements.
Here's what I suggest:

- type: custom:card-modder
  styles:
    - selector: cssSelectorHere
      style:
        --paper-card-background-color: rgba(0, 100, 0, 0.2)
        --paper-item-icon-color: white
    - selector: cssSelectorHere
      style:
        --paper-card-background-color: rgba(0, 100, 0, 0.2)
        --paper-item-icon-color: white
  card:

Thanks

**Comment by thomasloven** [comment]
It's something I've been working on for quite a while.

Yours is a good suggestion, but there's the problem of the shadow DOM. Most, but not all, cards use a shadowRoot, so I'd have to parse each step of the selector and check whether it exists or not before continuing. Worse yet, some cards have elements both inside and outside the shadowRoot, so I'd need to follow both branches... and so on.

**Comment by yosilevy** [comment]
Understood. Would be very valuable still and much appreciated by many people.

So maybe as a different approach you could:
* Add a way in hass-polymer to add IDs or classes on picture-element items as well as entities in the entities card for spot-on selection.
* Allow injecting a full style entry and not just a style attribute. 

If we can do that I think it will solve most scenarios.

**Comment by thomasloven** [comment]
https://github.com/thomasloven/lovelace-card-mod
