### ISSUE TITLE
Card modder with picture entities card

### ISSUE THREAD

**Issue by wendan20** [thomasloven/lovelace-card-modder#23]
Hi, I'm experimenting with card-modder and things look great! Much more flexibility! Thanks.

I'm struggling a bit with the picture entities card and specialy with the background image from this card. All the entities in the card are related to this background image. For example the position.

When working with card-modder I managed to change a lot of things, but I do not see how I can change this background image. For example the size, but als the opacity. When I change the background opacity with card-modder it changes the background colour behind the background image of the card.

Am I missing something? Thanks!

**Comment by thomasloven** [comment]
That can't be changed using card-modder at this point.
`card-modder` can only change the card itself, but in picture-entities the background image is laying on top of the card.
I suppose your best bet would be to make your image transparent in itself, if possible.

**Comment by wendan20** [comment]
Thanks! Thats what I thought. I will give it a try that way.


Op 3 februari 2019 bij 18:22:06, Thomas Lovén (notifications@github.com) schreef:

That can't be changed using card-modder at this point.
card-modder can only change the card itself, but in picture-entities the background image is laying on top of the card.
I suppose your best bet would be to make your image transparent in itself, if possible.

**Comment by thomasloven** [comment]
I'm leaving this issue open because I'm still thinking of ways to add this functionality to card-modder in the future.

**Comment by wendan20** [comment]
Super! I mangel the workaround with a transparent background image. But it’s pretty complicated with size positioning etc.

Are you aware of not working with the custom calendar card? When I use the calendar card with card modder I get “Custom element doesn’t exist: calendar card.”. Without the aardmodder it works fine.

Grtz


Op 4 februari 2019 bij 10:02:41, Thomas Lovén (notifications@github.com) schreef:

I'm leaving this issue open because I'm still thinking of ways to add this functionality to card-modder in the future.

**Comment by thomasloven** [comment]
Closing this anyway, because I realized the feature is the same as in #19. Still thinking about it. Recent experimental features of Chrome might make it viable in the future...
