### ISSUE TITLE
New feature: Force sizing Width of an element?

### ISSUE THREAD

**Issue by Tom-ahawk** [thomasloven/lovelace-card-modder#35]
Hopefully with time, the feature to be able to specify the % or pixel(?) of the width of a card, for an element (entity/picture/…).
So, one can specify in a horizontal stack that picure1 uses 30% (cell no 1), picure2 uses 40% (cell no 2), and sensor3 uses 30% (cell no 3), of the card’s width.

**Comment by thomasloven** [comment]
https://github.com/thomasloven/lovelace-layout-card#max-width

**Comment by Tom-ahawk** [comment]
I have been looking at this card. But if I understand correctly, you can define the width of a card, but not take a standard card and the divide this card up into cells with defined width(?).  

The reason I am locking for a card divider is to be able to group/align information. In my case, have my picture card (a square pic.) with speakers to the left for a markdown card displaying long  text lines. I whish...:

(red face comment from me)
![image](https://user-images.githubusercontent.com/35527507/56661134-67473b00-66a1-11e9-8193-3501a628743a.png)

![image](https://user-images.githubusercontent.com/35527507/56661161-729a6680-66a1-11e9-905e-d12c2319c9cd.png)

**Comment by thomasloven** [comment]
Then I believe picture-elements is the way to go.
You can put any card inside a picture-elements card and place it exactly as you want.
See https://github.com/thomasloven/hass-config/wiki/Misc-tricks#cardelemententity-row-triality

**Comment by Tom-ahawk** [comment]
Aha...I had no idea. 

Looking at the documentation I see that I can use your custom-markdown card (which is the top card I use in my stack) in the   picture-elements. 

Thanks, will try out!
