### ISSUE TITLE
Card Icon

### ISSUE THREAD

**Issue by brettlg** [thomasloven/lovelace-card-modder#39]
Is there a chance to have the option for a card icon to the right of the  card title similar to mini-graph-card circled in red on attached image?
This would give a yam config of...

- type: custom:card-modder
  name: SERVER
  icon: mdi:server
  entities:
    - entity: light.master_light

![Screen Shot 2019-06-12 at 10 46 43 am](https://user-images.githubusercontent.com/30974297/59316027-bc95e500-8cff-11e9-9dbb-91ef3e560747.png)

Thanks
Brett

**Comment by thomasloven** [comment]
Something like this, perhaps?

Don't hold your breath, but keep your eyes open...
![icon-headers](https://user-images.githubusercontent.com/1299821/59333150-0c70ae00-8cf8-11e9-8832-b11d1c8e3279.jpg)


![Skarmavbild_2019-05-20_kl _00 10 48](https://user-images.githubusercontent.com/1299821/59333010-d0d5e400-8cf7-11e9-87c7-24445855052f.png)
