### ISSUE TITLE
enable templates on style ?

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-modder#7]
HI,

Like te propose a feature request for style_templates if at all possible:

```
    style:
     background-image-template: >
      {% set path = 'url("/local/lovelace/images/weather-background_' %}
      {% set image = 'day' if is_state('sun.sun','above_horizon') else '_night' %}
      {% set ext = '.png")'%}
      {{path+image+ext}}
```

or

```
    style_template:
     background-image: >
      {% set path = 'url("/local/lovelace/images/weather-background_' %}
      {% set image = 'day' if is_state('sun.sun','above_horizon') else '_night' %}
      {% set ext = '.png")'%}
      {{path+image+ext}}
```
to allow for automatic state based style changes. Since I use these templates in current Tiles css formatting, I hope this would also be possible in the card-modder.

thanks for considering

**Comment by thomasloven** [comment]
I added a form of templating.
I'm *not* going to implement full jinja, but with this and a template sensor or two, you'd get the same functionality.

**Comment by Mariusthvdb** [comment]
thank you very much, like and need the flexibility this allows for now. magic.
